services:
    _defaults:
        autowire: true
        autoconfigure: true

    BisonLab\ContextBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Lib/'
            - '../src/Repository/ContextBaseRepository.php'
            - '../src/Service/ExternalRetriever.php'

    BisonLab\ContextBundle\Lib\Retriever\:
        resource: '../src/Lib/Retriever/'
        tags:
            - { name: 'bisonlab.context_owner_retriever' , index_by: 'key' }

    BisonLab\ContextBundle\Service\ExternalRetriever:
        autowire: true
        autoconfigure: true
        arguments: [!tagged_locator { tag: 'bisonlab.context_owner_retriever', index_by: 'key' }]

    bisonlab.context_retriever:
        alias: BisonLab\ContextBundle\Service\ExternalRetriever
        public: true
